const data = [

    {
      id: 0,
      title: "Quote Me, Senpai!",
      subtitle: "Anime Quote Quiz, API Usage, Materialize Framework",
      repoLink: "https://github.com/AbbyDabbyDooDoesGitHub/UW_Project1_QuoteMeSenpai",
      liveLink: "https://abbydabbydoodoesgithub.github.io/UW_Project1_QuoteMeSenpai/",
      featImg: "/assets/imgs/_project-imgs/QMS_screenshot_361by150.png",
      mobileFeatOrStdImg:   "/assets/imgs/_project-imgs/QMS_screenshot_262by175.png",
      altImg: "Preview of the 'Quote Me, Senpai' Web Application",
      featured: false,
    },

    {
      id: 1,
      title: "Password Generator",
      subtitle: "User Input, Alert/Confirm Windows, & Random Characters",
      repoLink: "https://github.com/AbbyDabbyDooDoesGitHub/UW_ChWk03_PasswordGenerator",
      liveLink: "https://abbydabbydoodoesgithub.github.io/UW_ChWk03_PasswordGenerator/",
      featImg: "/assets/imgs/_project-imgs/PasswordGen_Screenshot_361by150.png",
      mobileFeatOrStdImg: "/assets/imgs/_project-imgs/PasswordGen_Screenshot_262by175.png",
      altImg: "Preview of the Password Generator Web Application",
      featured: false,
    },

    {
      id: 2,
      title: "Web Accessibility Features",
      subtitle: "Add Accessibility Features, Adjust Layout, & Ensure Proper Functionality",
      repoLink: "https://github.com/AbbyDabbyDooDoesGitHub/UW_ChWk01_WebAccessibilityFeatures",
      liveLink: "https://abbydabbydoodoesgithub.github.io/UW_ChWk01_WebAccessibilityFeatures/",
      featImg: "/assets/imgs/_project-imgs/Accessibility_Screenshot_361by150.PNG",
      mobileFeatOrStdImg: "/assets/imgs/_project-imgs/Accessibility_Screenshot_262by175.PNG",
      altImg: "Preview of the Page Worked on for Accessibility Features (A Fake Company Landing Page)",
      featured: false,
    },

    {
      id: 3,
      title: "Hawkshot: Gaming Friend Tracker",
      subtitle: "Full Stack React Application Deployed on Heroku",
      repoLink: "https://github.com/AbbyDabbyDooDoesGitHub/UW_Project3_LeagueOfLegendsFriendTracker",
      liveLink: "https://hawkshot-friend-tracker.herokuapp.com/",
      featImg: "/assets/imgs/_project-imgs/Hawkshot_screenshot_361by150.png",
      mobileFeatOrStdImg: "/assets/imgs/_project-imgs/Hawkshot_screenshot_262by175.png",
      altImg: "Preview of Hawkshot",
      featured: true,
    },

    {
      id: 4,
      title: "HTML & CSS Portfolio",
      subtitle: "Professional Portfolio using html, css, & js",
      repoLink: "https://github.com/AbbyDabbyDooDoesGitHub/UW_ChWk02_MyProfessionalPortfolio",
      liveLink: "https://abbydabbydoodoesgithub.github.io/UW_ChWk02_MyProfessionalPortfolio/",
      featImg: "/assets/imgs/_project-imgs/HTMLPortfolio_screenshot_361by150.png",
      mobileFeatOrStdImg: "/assets/imgs/_project-imgs/HTMLPortfolio_screenshot_262by175.png",
      altImg: "Preview of the HTML Portfolio",
      featured: false,
    },

    {
      id: 5,
      title: "Interactive Quiz",
      subtitle: "Interactive quiz featuring a timer functionality",
      repoLink: "https://github.com/AbbyDabbyDooDoesGitHub/UW_ChWk04_InteractiveQuiz",
      liveLink: "https://abbydabbydoodoesgithub.github.io/UW_ChWk04_InteractiveQuiz/",
      featImg: "/assets/imgs/_project-imgs/InteractiveQuiz_screenshot_361by150.png",
      mobileFeatOrStdImg: "/assets/imgs/_project-imgs/InteractiveQuiz_screenshot_262by175.png",
      altImg: "Preview of the Interactive Quiz",
      featured: false,
    },

    {
      id: 6,
      title: "Workday Scheduler",
      subtitle: "Dynamic Scheduler using jQuery & local storage",
      repoLink: "https://github.com/AbbyDabbyDooDoesGitHub/UW_ChWk05_WorkDayScheduleCalendar",
      liveLink: "https://abbydabbydoodoesgithub.github.io/UW_ChWk05_WorkDayScheduleCalendar/",
      featImg: "/assets/imgs/_project-imgs/WorkScheduler_screenshot_361by150.png",
      mobileFeatOrStdImg: "/assets/imgs/_project-imgs/WorkScheduler_screenshot_262by175.png",
      altImg: "Preview of the Workday Scheduler",
      featured: false,
    },

    {
      id: 7,
      title: "Weather Dashboard",
      subtitle: "Dynamic Weather Dashboard using Third-Party API data",
      repoLink: "https://github.com/AbbyDabbyDooDoesGitHub/UW_ChWk06_ServerSideAPI-WeatherDashboard",
      liveLink: "https://abbydabbydoodoesgithub.github.io/UW_ChWk06_ServerSideAPI-WeatherDashboard/",
      featImg: "/assets/imgs/_project-imgs/WeatherDash_screenshot_361by150.png",
      mobileFeatOrStdImg: "/assets/imgs/_project-imgs/WeatherDash_screenshot_262by175.png",
      altImg: "Preview of the Weather Dashboard",
      featured: false,
    },

    {
      id: 8,
      title: "Professional ReadMe Generator",
      subtitle: "Command Line ReadMe Generator using Inquirer.js",
      repoLink: "https://github.com/AbbyDabbyDooDoesGitHub/UW_ChWk09_ProfessionalReadMeGenerator",
      liveLink: "https://www.youtube.com/watch?v=M7wFUsmOsSk",
      featImg: "/assets/imgs/_project-imgs/ReadMeGen_screenshot_361by150.png",
      mobileFeatOrStdImg: "/assets/imgs/_project-imgs/ReadMeGen_screenshot_262by175.png",
      altImg: "Preview of the Professional ReadMe Generator Demo on Youtube.com",
      featured: false,
    },

    {
      id: 9,
      title: "Team Profile Generator",
      subtitle: "Command Line Team Profile Generator using Inquirer.js",
      repoLink: "https://github.com/AbbyDabbyDooDoesGitHub/UW_ChWk10_TeamProfileGenerator",
      liveLink: "https://www.youtube.com/watch?v=cYn3SDIv0MQ",
      featImg: "/assets/imgs/_project-imgs/TeamProfileGen_screenshot_361by150.png",
      mobileFeatOrStdImg: "/assets/imgs/_project-imgs/TeamProfileGen_screenshot_262by175.png",
      altImg: "Preview of the Team Profile Generator Demo on Youtube.com",
      featured: false,
    },

    // {
    //   id: 10,
    //   title: "Note Taker",
    //   subtitle: "Note Taker using Express.js",
    //   repoLink: "https://github.com/AbbyDabbyDooDoesGitHub/UW_ChWk11_Express.jsNoteTaker",
    //   liveLink: "",
    //   featImg: "/assets/imgs/_generic-imgs/Light_Purple_Rounded_Blob_Swirl.jpg",
    //   mobileFeatOrStdImg: "/assets/imgs/_generic-imgs/Light_Purple_Rounded_Blob_Swirl.jpg",
    //   altImg: "Light Purple Rounded Swirl",
    //   featured: false,
    // },

    // {
    //   id: 11,
    //   title: "Employee Tracker",
    //   subtitle: "Command Line Interface using Node.js, Inquirer.js, & MySQL",
    //   repoLink: "https://github.com/AbbyDabbyDooDoesGitHub/UW_ChWk12_SQLChallenge_EmployeeTracker",
    //   liveLink: "",
    //   featImg: "/assets/imgs/_generic-imgs/Light_Purple_Rounded_Blob_Swirl.jpg",
    //   mobileFeatOrStdImg: "/assets/imgs/_generic-imgs/Light_Purple_Rounded_Blob_Swirl.jpg",
    //   altImg: "Light Purple Rounded Swirl",
    //   featured: false,
    // },

    // {
    //   id: 12,
    //   title: "E-Commerce BackEnd",
    //   subtitle: "Express.js API using Sequelize to interact with MySQL database",
    //   repoLink: "https://github.com/AbbyDabbyDooDoesGitHub/UW_ChWk13_ObjectRelationalMapping_E-commerceBackEnd",
    //   liveLink: "",
    //   featImg: "/assets/imgs/_generic-imgs/Light_Purple_Rounded_Blob_Swirl.jpg",
    //   mobileFeatOrStdImg: "/assets/imgs/_generic-imgs/Light_Purple_Rounded_Blob_Swirl.jpg",
    //   altImg: "Light Purple Rounded Swirl",
    //   featured: false,
    // },

    // {
    //   id: 13,
    //   title: "Tech Blog",
    //   subtitle: "CMS-style blog site following MVC paradigm",
    //   repoLink: "https://github.com/AbbyDabbyDooDoesGitHub/UW_ChWk14_Model-View-Controller_TechBlog-OPTIONAL",
    //   liveLink: "",
    //   featImg: "/assets/imgs/_generic-imgs/Light_Purple_Rounded_Blob_Swirl.jpg",
    //   mobileFeatOrStdImg: "/assets/imgs/_generic-imgs/Light_Purple_Rounded_Blob_Swirl.jpg",
    //   altImg: "Light Purple Rounded Swirl",
    //   featured: false,
    // },

    {
      id: 14,
      title: "Anatomy of a Hex Regex",
      subtitle: "Practiced Writing about Code in GitHub Gist",
      repoLink: "https://github.com/AbbyDabbyDooDoesGitHub/UW_ChWk17_RegexTutorial-WritingAboutCode",
      liveLink: "https://gist.github.com/AbbyDabbyDooDoesGitHub/03a7b598c464ac1872a66e4309b6a48b",
      featImg: "/assets/imgs/_project-imgs/AnatomyOfAHexRegex_screenshot_361by150.png",
      mobileFeatOrStdImg: "/assets/imgs/_project-imgs/AnatomyOfAHexRegex_screenshot_262by175.png",
      altImg: "Preview of GitHub Gist",
      featured: false,
    },

    // {
    //   id: 15,
    //   title: "Social Network API",
    //   subtitle: "Social Network API using Express.js, Mongoose, & MongoDB",
    //   repoLink: "https://github.com/AbbyDabbyDooDoesGitHub/UW_ChWk18_SocialNetworkAPI-NoSQL",
    //   liveLink: "",
    //   featImg: "/assets/imgs/_generic-imgs/Light_Purple_Rounded_Blob_Swirl.jpg",
    //   mobileFeatOrStdImg: "/assets/imgs/_generic-imgs/Light_Purple_Rounded_Blob_Swirl.jpg",
    //   altImg: "Light Purple Rounded Swirl",
    //   featured: false,
    // },

    // {
    //   id: 16,
    //   title: "Text Editor",
    //   subtitle: "Progressive Web Applications",
    //   repoLink: "https://github.com/AbbyDabbyDooDoesGitHub/UW_ChWk19_TextEditor-ProgressiveWebApplications",
    //   liveLink: "",
    //   featImg: "/assets/imgs/_generic-imgs/Light_Purple_Rounded_Blob_Swirl.jpg",
    //   mobileFeatOrStdImg: "/assets/imgs/_generic-imgs/Light_Purple_Rounded_Blob_Swirl.jpg",
    //   altImg: "Light Purple Rounded Swirl",
    //   featured: false,
    // },

    // {
    //   id: 17,
    //   title: "Book Search Engine",
    //   subtitle: "",
    //   repoLink: "https://github.com/AbbyDabbyDooDoesGitHub/UW_ChWk21_MERN-BookSearchEngine",
    //   liveLink: "",
    //   featImg: "/assets/imgs/_generic-imgs/Light_Purple_Rounded_Blob_Swirl.jpg",
    //   mobileFeatOrStdImg: "/assets/imgs/_generic-imgs/Light_Purple_Rounded_Blob_Swirl.jpg",
    //   altImg: "Light Purple Rounded Swirl",
    //   featured: false,
    // },

    // {
    //   id: 18,
    //   title: "",
    //   subtitle: "",
    //   repoLink: "https://github.com/AbbyDabbyDooDoesGitHub/UW_ChWk22_StateChallenge-ReduxStore-OPTIONAL",
    //   liveLink: "",
    //   featImg: "/assets/imgs/_generic-imgs/Light_Purple_Rounded_Blob_Swirl.jpg",
    //   mobileFeatOrStdImg: "/assets/imgs/_generic-imgs/Light_Purple_Rounded_Blob_Swirl.jpg",
    //   altImg: "Light Purple Rounded Swirl",
    //   featured: false,
    // },

    // {
    //   id: 19,
    //   title: "",
    //   subtitle: "",
    //   repoLink: "https://github.com/AbbyDabbyDooDoesGitHub/UW_ChWk22_StateChallenge-ReduxStore-OPTIONAL",
    //   liveLink: "",
    //   featImg: "/assets/imgs/_generic-imgs/Light_Purple_Rounded_Blob_Swirl.jpg",
    //   mobileFeatOrStdImg: "/assets/imgs/_generic-imgs/Light_Purple_Rounded_Blob_Swirl.jpg",
    //   altImg: "Light Purple Rounded Swirl",
    //   featured: false,
    // },

    // {
    //   id: 20,
    //   title: "Project Review App",
    //   subtitle: "",
    //   repoLink: "https://github.com/AbbyDabbyDooDoesGitHub/UW_Project2_BootcampProjectReviewApp_Fork",
    //   liveLink: "https://proj2-app.herokuapp.com/",
    //   featImg: "/assets/imgs/_generic-imgs/Light_Purple_Rounded_Blob_Swirl.jpg",
    //   mobileFeatOrStdImg: "/assets/imgs/_generic-imgs/Light_Purple_Rounded_Blob_Swirl.jpg",
    //   altImg: "Light Purple Rounded Swirl",
    //   featured: false,
    // },

    {
      id: 21,
      title: "React.js Portfolio",
      subtitle: "Checkout the GitHub Repo for this Portfolio!",
      repoLink: "https://github.com/AbbyDabbyDooDoesGitHub/reactportfolioapp",
      liveLink: "",
      featImg: "/assets/imgs/_project-imgs/HTMLPortfolio_screenshot_361by150.png",
      mobileFeatOrStdImg: "/assets/imgs/_project-imgs/HTMLPortfolio_screenshot_262by175.png",
      altImg: "Preview of the React.js Portfolio",
      featured: false,
    },


  ];
  
  export default data;
  